(()=>{"use strict";
const S=()=>window.SIP_ADJUDICACION_STORAGE;
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const key=r=>S()?.plazaKey(r)||"";
const title=r=>r?.oficial_minsa?.establecimiento||r?.oficial_minsa?.institucion||"Plaza SERUMS";
const loc=r=>[r?.oficial_minsa?.distrito,r?.oficial_minsa?.provincia,r?.oficial_minsa?.departamento].filter(Boolean).join(" · ");
const allPlans=st=>["A","B","C"].flatMap(p=>(st.planes?.[p]||[]).map(r=>({plan:p,row:r})));
const CHECKS=[
 ["evaluacion","Contar con la evaluación SERUMS exigida para la convocatoria"],
 ["oferta","Revisar la oferta oficial de plazas antes de postular"],
 ["datos","Verificar cuidadosamente los datos personales y profesionales antes de registrar la inscripción"],
 ["aptitud","Comprobar la publicación oficial de condición apto/no apto"],
 ["programa","Revisar el programa y horario oficial de adjudicación de la modalidad correspondiente"],
 ["documentos","Revisar los documentos de formalización exigidos por la entidad de la plaza adjudicada"]
];
function renderChecklist(){const h=document.getElementById("sip-requisitos");if(!h||!S())return;const st=S().read();h.innerHTML=`<div class="sip-flow-head"><div><h2>Preparación para adjudicación</h2><p>Checklist operativo basado en el proceso oficial SERUMS 2026-I. Confirma siempre la convocatoria vigente.</p></div><span class="sip-badge">Apoyo a la decisión</span></div><div class="sip-checks">${CHECKS.map(([id,t])=>`<label class="sip-check"><input type="checkbox" data-check="${id}" ${st.checklist?.[id]?"checked":""}><span>${esc(t)}</span></label>`).join("")}</div><div class="sip-warning"><strong>2026-I:</strong> la inscripción fue responsabilidad del postulante; no hubo reinscripciones, lista de observados, etapa de subsanación ni casos especiales. Para otra convocatoria, verifica el instructivo vigente.</div><div class="sip-source-links"><a href="https://www.gob.pe/institucion/minsa/informes-publicaciones/8040033-instructivo-del-proceso-de-adjudicacion-de-plazas-para-el-serums-2026-i" target="_blank" rel="noopener">Instructivo oficial</a><a href="https://www.gob.pe/institucion/minsa/informes-publicaciones/8050582" target="_blank" rel="noopener">Manual oficial</a><a href="https://www.gob.pe/114543-documentos-de-consulta-del-proceso-de-adjudicacion-de-plazas-para-el-serums-2026-i" target="_blank" rel="noopener">Documentos del proceso</a></div>`;h.querySelectorAll("[data-check]").forEach(x=>x.onchange=()=>S().setChecklist(x.dataset.check,x.checked));}
function renderSimulator(){const h=document.getElementById("sip-simulador");if(!h||!S())return;const st=S().read(),items=allPlans(st);h.innerHTML=`<div class="sip-flow-head"><div><h2>Simulador de adjudicación</h2><p>Ensaya decisiones según tu orden de mérito y el estado que tú marques durante la simulación.</p></div><span class="sip-badge sip-badge-warn">SIMULACIÓN</span></div><div class="sip-sim-grid"><label>Orden de mérito<input id="sip-orden" type="number" min="1" inputmode="numeric" value="${esc(st.simulacion?.ordenMerito||"")}" placeholder="Ej. 125"></label><label>Personas antes de tu turno<input id="sip-antes" type="number" min="0" inputmode="numeric" value="${esc(st.simulacion?.personasAntes||0)}"></label></div><div class="sip-sim-list">${items.map(({plan,row})=>`<label class="sip-sim-row"><input type="checkbox" data-ocupada="${esc(key(row))}"><span><b>Plan ${plan} · ${esc(title(row))}</b><small>${esc(loc(row))}</small></span><em>Marcar ocupada en simulación</em></label>`).join("")||'<div class="empty-state">Primero guarda plazas y clasifícalas en Plan A, B o C.</div>'}</div><div class="sip-actions"><button class="primary" id="sip-ejecutar" ${items.length?"":"disabled"}>Simular mi turno</button></div><div id="sip-sim-result"></div><div class="sip-warning">Este simulador no consulta disponibilidad oficial en tiempo real. Una plaza solo se considera ocupada aquí cuando tú la marcas para ensayar un escenario.</div>`;const btn=document.getElementById("sip-ejecutar");if(btn)btn.onclick=()=>{const ocupadas=[...h.querySelectorAll("[data-ocupada]:checked")].map(x=>x.dataset.ocupada),r=window.SIP_ADJUDICACION_SIMULADOR.create({ordenMerito:document.getElementById("sip-orden").value,personasAntes:document.getElementById("sip-antes").value,ocupadas}),box=document.getElementById("sip-sim-result");box.innerHTML=r.siguiente?`<div class="sip-result-ok"><b>Siguiente alternativa disponible en este escenario:</b><strong>Plan ${esc(r.siguiente.plan)} · ${esc(title(r.siguiente.plaza))}</strong><span>${esc(loc(r.siguiente.plaza))}</span></div>`:`<div class="sip-result-stop"><b>En este escenario no queda ninguna alternativa de tus Planes A/B/C.</b><span>Revisa más plazas antes del turno real.</span></div>`;};}
function renderReal(){const h=document.getElementById("sip-modo-real");if(!h||!S())return;const st=S().read(),items=allPlans(st),ad=st.adjudicada;h.innerHTML=`<div class="sip-flow-head"><div><h2>Modo adjudicación real</h2><p>Ten tus alternativas preparadas durante la adjudicación oficial.</p></div><span class="sip-badge sip-badge-danger">NO ES DISPONIBILIDAD EN VIVO</span></div>${ad?`<div class="sip-result-ok"><b>Plaza marcada como adjudicada</b><strong>${esc(title(ad))}</strong><span>${esc(loc(ad))}</span><button id="sip-desmarcar">Corregir selección</button></div>`:`<div class="sip-real-list">${items.map(({plan,row})=>`<article><div><b>Plan ${plan} · ${esc(title(row))}</b><small>${esc(loc(row))}</small></div><button data-adjudicar="${esc(key(row))}">Marcar como adjudicada</button></article>`).join("")||'<div class="empty-state">No hay alternativas clasificadas.</div>'}</div>`}<div class="sip-warning">Contrasta la disponibilidad con el canal oficial de adjudicación. Esta herramienta no reserva, bloquea ni confirma plazas.</div>`;h.querySelectorAll("[data-adjudicar]").forEach(b=>b.onclick=()=>{const row=items.find(x=>key(x.row)===b.dataset.adjudicar)?.row;if(row){S().setAdjudicada(row);emitBridge(row)}});const d=document.getElementById("sip-desmarcar");if(d)d.onclick=()=>S().setAdjudicada(null);}
function makeContext(row){const x=row?.oficial_minsa||{};return {source:"SIP_ADJUDICACION",version:1,convocatoria:row?.convocatoria||null,modalidad:row?.modalidad||null,plazaId:row?.id||null,profesion:x.profesion||null,establecimiento:x.establecimiento||null,institucion:x.institucion||null,categoria:x.categoria||null,gradoDificultad:x.grado_dificultad||null,renipress:x.codigo_renipress||null,departamento:x.departamento||null,provincia:x.provincia||null,distrito:x.distrito||null,zaf:x.zaf||null,ze:x.ze||null,createdAt:new Date().toISOString()};}
function emitBridge(row){if(!row||!S())return;const ctx=makeContext(row);S().setContexto247(ctx);dispatchEvent(new CustomEvent("sip:adjudicacion:adjudicada",{detail:ctx}));}
function renderPost(){const h=document.getElementById("sip-post");if(!h||!S())return;const st=S().read(),r=st.adjudicada;if(!r){h.innerHTML=`<div class="sip-flow-head"><div><h2>Postadjudicación → 24/7 Día SERUMS</h2><p>Se activa cuando marques la plaza realmente adjudicada.</p></div></div><div class="empty-state">Aún no has marcado una plaza adjudicada.</div>`;return}const ctx=makeContext(r);h.innerHTML=`<div class="sip-flow-head"><div><h2>Postadjudicación → 24/7 Día SERUMS</h2><p>La plaza adjudicada se convierte en contexto territorial y profesional reutilizable.</p></div><span class="sip-badge">CONTEXTO LISTO</span></div><div class="sip-post-card"><h3>${esc(title(r))}</h3><p>${esc(loc(r))}</p><div class="sip-context-grid"><span><b>Profesión</b>${esc(ctx.profesion||"—")}</span><span><b>Modalidad</b>${esc(ctx.modalidad||"—")}</span><span><b>Categoría</b>${esc(ctx.categoria||"—")}</span><span><b>GD</b>${esc(ctx.gradoDificultad||"—")}</span><span><b>RENIPRESS</b>${esc(ctx.renipress||"—")}</span><span><b>Institución</b>${esc(ctx.institucion||"—")}</span></div></div><div class="sip-next"><b>Siguientes acciones</b><label><input type="checkbox"> Verificar documentación de formalización con la entidad adjudicada</label><label><input type="checkbox"> Confirmar fecha, lugar y condiciones de incorporación</label><label><input type="checkbox"> Completar inducción/capacitación que corresponda</label></div><div class="sip-actions"><button class="primary" id="sip-preparar247">Preparar contexto 24/7</button><button id="sip-copiar247">Copiar contexto JSON</button></div><textarea id="sip-contexto-json" readonly>${esc(JSON.stringify(ctx,null,2))}</textarea><div class="sip-warning">El puente genera el contexto de entrada para 24/7. La recepción automática por SERUM-APP requiere que ese proyecto implemente el receptor del evento/JSON; no se simula una integración que todavía no exista.</div>`;document.getElementById("sip-preparar247").onclick=()=>emitBridge(r);document.getElementById("sip-copiar247").onclick=async()=>{try{await navigator.clipboard.writeText(JSON.stringify(ctx,null,2));document.getElementById("sip-copiar247").textContent="Copiado ✓"}catch{document.getElementById("sip-contexto-json").select()}};}
function renderAll(){renderChecklist();renderSimulator();renderReal();renderPost()}
addEventListener("sip:adjudicacion:state",renderAll);addEventListener("sip:adjudicacion:alternativas",()=>setTimeout(renderAll,0));document.addEventListener("DOMContentLoaded",renderAll);window.SIP_ADJUDICACION_FLUJO=Object.freeze({render:renderAll,makeContext});
})();
