(()=>{"use strict";
const $=id=>document.getElementById(id),ui={count:$("geo-count"),estado:$("geo-estado"),map:$("mapa-alternativas"),rutas:$("geo-rutas"),gps:$("geo-mi-ubicacion"),elegir:$("geo-elegir-origen"),limpiar:$("geo-limpiar-origen")};
if(Object.values(ui).some(x=>!x)||!window.L||!window.SERUMSRoutes)return;
const GEO="https://geominsa.minsa.gob.pe/geominsaserver/rest/services/SRV_DGAIN_DIPOS/SRV_DIPOS_GeoRIS_RENIPRESSPeru/MapServer/0/query",cache=new Map();
let alternativas=[],guardadas=[],map=L.map(ui.map).setView([-9.2,-75.2],5),capa=L.layerGroup().addTo(map),origen=null,markerOrigen=null,elegirOrigen=false,renderId=0;
L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"© OpenStreetMap contributors"}).addTo(map);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const esMINEDU=r=>String(r?.oficial_minsa?.institucion||"").trim().toUpperCase()==="MINEDU";
async function geo(r){if(esMINEDU(r))return null;const c=String(r?.oficial_minsa?.codigo_renipress||"").trim();if(!c)return null;if(cache.has(c))return cache.get(c);const p=new URLSearchParams({where:`Código_Único='${c.replace(/'/g,"''")}'`,outFields:"Código_Único,Nombre_del_establecimiento,Departamento,Provincia,Distrito,Dirección,Estado",returnGeometry:"true",outSR:"4326",f:"geojson"}),res=await fetch(`${GEO}?${p}`);if(!res.ok)throw Error(`GeoMINSA HTTP ${res.status}`);const d=await res.json(),f=d.features?.[0];if(!f?.geometry?.coordinates)return null;const [lon,lat]=f.geometry.coordinates,g={lat:+lat,lon:+lon,attrs:f.properties||{}};cache.set(c,g);return g}
const iconoOrigen=L.divIcon({className:"",html:'<div class="origin-pin" title="Origen"></div>',iconSize:[24,24],iconAnchor:[12,24],popupAnchor:[0,-24]});
function setOrigen(lat,lon,label){origen={lat:+lat,lon:+lon,label};if(markerOrigen)markerOrigen.remove();markerOrigen=L.marker([origen.lat,origen.lon],{icon:iconoOrigen,zIndexOffset:1000}).addTo(map).bindPopup(`<b>Origen del viaje</b><br>${esc(label)}`);ui.limpiar.disabled=false}
const tiempo=min=>{const m=Math.max(0,Math.round(Number(min)||0)),h=Math.floor(m/60),r=m%60;return h?`${h} h ${r} min`:`${r} min`};
async function render(){const id=++renderId;capa.clearLayers();ui.rutas.innerHTML="";if(!alternativas.length){ui.count.textContent="0 ubicadas";ui.estado.textContent="Guarda alternativas para ubicarlas mediante RENIPRESS.";return}ui.estado.textContent="Consultando GeoMINSA/RENIPRESS…";const gs=[];for(const r of alternativas){try{const g=await geo(r);if(g)gs.push({r,g})}catch(err){console.warn(err)}}ui.count.textContent=`${gs.length} ubicada${gs.length===1?"":"s"}`;const bounds=[];gs.forEach(({r,g})=>{const x=r.oficial_minsa;L.marker([g.lat,g.lon]).addTo(capa).bindPopup(`<b>${esc(x.establecimiento)}</b><br>${esc(x.distrito)} · ${esc(x.provincia)}<br>RENIPRESS ${esc(x.codigo_renipress)}`);bounds.push([g.lat,g.lon])});if(origen)bounds.push([origen.lat,origen.lon]);if(bounds.length)map.fitBounds(bounds,{padding:[25,25],maxZoom:12});if(!origen){ui.estado.textContent=gs.length?`${gs.length} alternativa(s) ubicadas. Define tu origen para calcular rutas.`:"No se encontraron coordenadas RENIPRESS para estas alternativas.";return}ui.estado.textContent="Calculando rutas…";const out=[];for(const a of gs){let ruta=null;try{ruta=await SERUMSRoutes.carretera(origen,a.g)}catch(err){console.warn(err)}out.push({...a,ruta,recta:SERUMSRoutes.recta(origen,a.g)})}if(id!==renderId)return;ui.rutas.innerHTML=`<div class="route-origin">📍 Rutas desde: ${esc(origen.label)}</div>`+out.map((a,i)=>{const x=a.r.oficial_minsa;return `<article class="route-item"><strong>${i+1}. ${esc(x.establecimiento)}</strong><div>${esc(x.distrito)} · ${esc(x.provincia)} · ${esc(x.departamento)}</div><div class="route-metrics">${a.ruta?`<span><b>${a.ruta.km.toFixed(1)} km</b><br><small>ruta estimada</small></span><span><b>${tiempo(a.ruta.min)}</b><br><small>tiempo estimado</small></span>`:`<span><b>${a.recta.toFixed(1)} km</b><br><small>línea recta</small></span>`}</div><div class="route-actions"><button data-map="${i}">Ver en mapa</button><a target="_blank" rel="noopener" href="${SERUMSRoutes.google(origen,a.g)}">Cómo llegar</a></div></article>`}).join("");ui.rutas.querySelectorAll("[data-map]").forEach(b=>b.onclick=()=>{const a=out[+b.dataset.map];map.setView([a.g.lat,a.g.lon],14);ui.map.scrollIntoView({behavior:"smooth",block:"center"})});ui.estado.textContent=`Análisis desde: ${origen.label}.`}
window.addEventListener("serums:alternativas",ev=>{guardadas=Array.isArray(ev.detail?.alternativas)?ev.detail.alternativas:[];alternativas=[...guardadas];render()});
window.addEventListener("serums:seleccion",ev=>{
  const seleccion=Array.isArray(ev.detail?.alternativas)?ev.detail.alternativas:[];
  alternativas=seleccion.length?seleccion:[...guardadas];
  render();
});
ui.gps.onclick=()=>{if(!navigator.geolocation){ui.estado.textContent="Geolocalización no disponible.";return}ui.estado.textContent="Solicitando ubicación…";navigator.geolocation.getCurrentPosition(p=>{setOrigen(p.coords.latitude,p.coords.longitude,"Mi ubicación");render()},err=>ui.estado.textContent=`No se pudo obtener la ubicación: ${err.message}`,{enableHighAccuracy:true,timeout:12000,maximumAge:60000})};
ui.elegir.onclick=()=>{elegirOrigen=true;ui.estado.textContent="Toca sobre el mapa el lugar desde donde deseas iniciar tu viaje.";ui.map.scrollIntoView({behavior:"smooth",block:"center"})};
map.on("click",ev=>{if(!elegirOrigen)return;elegirOrigen=false;setOrigen(ev.latlng.lat,ev.latlng.lng,`Origen seleccionado (${ev.latlng.lat.toFixed(4)}, ${ev.latlng.lng.toFixed(4)})`);render()});
ui.limpiar.onclick=()=>{origen=null;elegirOrigen=false;if(markerOrigen){markerOrigen.remove();markerOrigen=null}ui.limpiar.disabled=true;render()};
setTimeout(()=>map.invalidateSize(),250);
})();
